<a href="https://colab.research.google.com/github/Nikuson123/Nikuson123/blob/main/ruToxic_rubert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers sentencepiece --quiet
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_checkpoint = 'cointegrated/rubert-tiny-toxicity'
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)
model = AutoModelForSequenceClassification.from_pretrained(model_checkpoint)
if torch.cuda.is_available():
    model.cuda()
    
def text2toxicity(text, aggregate=True):
    """ Calculate toxicity of a text (if aggregate=True) or a vector of toxicity aspects (if aggregate=False)"""
    with torch.no_grad():
        inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True).to(model.device)
        proba = torch.sigmoid(model(**inputs).logits).cpu().numpy()
    if isinstance(text, str):
        proba = proba[0]
    if aggregate:
        return 1 - proba.T[0] * (1 - proba.T[-1])
    return proba

     |████████████████████████████████| 3.5 MB 21.0 MB/s 
     |████████████████████████████████| 1.2 MB 49.4 MB/s 
     |████████████████████████████████| 895 kB 49.8 MB/s 
     |████████████████████████████████| 596 kB 58.1 MB/s 
     |████████████████████████████████| 6.8 MB 56.6 MB/s 
     |████████████████████████████████| 67 kB 5.5 MB/s 


Downloading:   0%|          | 0.00/377 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/235k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/457k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/957 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/45.0M [00:00<?, ?B/s]

0.029058612592846256
[9.9849582e-01 6.1764085e-04 1.4417995e-03 6.0966657e-04 2.7595939e-02]
[0.02905864 0.01472682]
[[9.9849582e-01 6.1764085e-04 1.4417986e-03 6.0966657e-04 2.7595926e-02]
 [8.9890987e-01 1.2116299e-01 4.5758148e-04 2.8046436e-04 5.4803020e-01]]


In [2]:
print(text2toxicity('я люблю тебя', True))
# 0.029058612592846256

print(text2toxicity('я люблю тебя', False))
# [9.9849582e-01 6.1764085e-04 1.4417995e-03 6.0966657e-04 2.7595939e-02]

print(text2toxicity(['я люблю тебя', 'я люблю лето'], True))
# [0.02905864 0.01472682]

print(text2toxicity(['я люблю тебя', 'иди нафиг'], False))
# [[9.9849582e-01 6.1764085e-04 1.4417986e-03 6.0966657e-04 2.7595926e-02]
#  [8.9890987e-01 1.2116299e-01 4.5758148e-04 2.8046436e-04 5.4803020e-01]]  

0.029058612592846256
[9.9849582e-01 6.1764085e-04 1.4417995e-03 6.0966657e-04 2.7595939e-02]
[0.02905864 0.01472682]
[[9.9849582e-01 6.1764085e-04 1.4417986e-03 6.0966657e-04 2.7595926e-02]
 [8.9890987e-01 1.2116299e-01 4.5758148e-04 2.8046436e-04 5.4803020e-01]]
